'use client'
import { Inter } from 'next/font/google'
import style from './page.module.css'
import './globals.css'
import { useState } from 'react'
import Navbar from './Components/Navbar'
import Footer from './Components/Footer'
import 'bootstrap/dist/css/bootstrap.css'
import Home from './Home/page'
import Login from './login/page'
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [token, setToken] = useState(55)
  const handleToken = (token) => {
    setToken(token)
  }

  return (
    <Login.Provider value={{ token, handleToken }}>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </Login.Provider>

  )
}
